name: Build, Test, Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build-And-Test:
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: setup-environment
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn build
      - run: yarn lint
      - run: yarn format:check
      - run: yarn test
