name: Commitlint Workflow

on:
  pull_request:
    branches: [main]

jobs:
  Check-Commit-Message:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: setup-environment
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
